spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/bragi"
    username: "jason"
    password: "jason"
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    generate-ddl: "true"
management:
  server:
    port: 8081
    address: 127.0.0.1
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
retry:
  max-attempts: 3
  min-wait-between-millis: 1000
  max-wait-between-millis: 10000
server:
  port: 8089
